function init(){
	var page = window.location['pathname'].split('/');
  if(page[2] =='' || page[2] == 'index.html')
  	loadPagina('main');
}
function loadPagina(pagina) {
	
  $('#conteudo').load(pagina+'.html');
  var page = window.location['href'];
  $('ul.nav.navbar-nav > li.active').removeClass('active');
  $('ul.nav.navbar-nav > #'+pagina).addClass('active');

}
function showMenu() {
	var menu = '<nav class="navbar navbar-default navbar-fixed-top">'
  	+'<div class="top-bar"></div>'
			+'<div class="container-fluid">'
		  +'<!-- Brand and toggle get grouped for better mobile display -->'
		    +'<div class="navbar-header">'
		      +'<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">'
		        +'<span class="sr-only">Toggle navigation</span>'
		        +'<span class="icon-bar"></span>'
		        +'<span class="icon-bar"></span>'
		        +'<span class="icon-bar"></span>'
		      +'</button>'
		      +'<a class="navbar-brand" onclick="loadPagina(\'main\')">'
		      	+'<img src="img/logo.png" alt="clean & clear">'
		      +'</a>'
		    +'</div>'
		    +'<!-- Collect the nav links, forms, and other content for toggling -->'
		    +'<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">'
		      +'<ul class="nav navbar-nav">'
		        +'<li class="active" id="main"><a onclick="loadPagina(\'main\')">Home</a></li>'
		        +'<li id="about"><a onclick="loadPagina(\'about\')">About</a></li>'
		        +'<li class="dropdown" id="innovate">'
		          +'<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Innovate <span class="caret"></span></a>'
		          +'<ul class="dropdown-menu">'
		            +'<li><a onclick="loadPagina(\'innovate\')">Learn</a></li>'
		            +'<li><a onclick="loadPagina(\'innovate\')">Create</a></li>'
		            +'<li><a onclick="loadPagina(\'innovate\')">Teach</a></li>'
		          +'</ul>'
		        +'</li>'
		        +'<li id="blog"><a onclick="loadPagina(\'blog\')">Blog</a></li>'
		        +'<li id="contact"><a onclick="loadPagina(\'contact\')">Contact</a></li>'
		      +'</ul>'
		      +'<ul class="nav navbar-nav navbar-right">'
		      	+'<form class="navbar-form navbar-left" role="search">'
			       +' <div class="form-group">'
			          +'<input type="text" class="form-control" placeholder="Search">'
			        +'</div>'
			        +'<button type="submit" class="btn btn-default">Submit</button>'
			      +'</form>'
		        +'<li class="login" data-toggle="modal" data-target="#loginModal"><a href="#">Login</a></li>'
		        +'<li class="register" data-toggle="modal" data-target="#regModal"><a href="#">Register</a></li>'
		      +'</ul>'
		    +'</div><!-- /.navbar-collapse -->'
		  +'</div><!-- /.container-fluid -->'
		+'</nav>';
  return menu;
}
function showModals() {
	var modals = '<!-- Login Modal -->'
		+'<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel">'
		  +'<div class="modal-dialog" role="document">'
		    +'<div class="modal-content">'
		      +'<div class="modal-header">'
		        +'<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>'
		        +'<h4 class="modal-title" id="loginModalLabel">Login Form</h4>'
		      +'</div>'
		      +'<div class="modal-body">'
		      	+'<form class="form-horizontal">'
						  +'<div class="form-group">'
						    +'<label for="inputEmail3" class="col-sm-2 control-label">Email</label>'
						    +'<div class="col-sm-10">'
						      +'<input type="email" class="form-control" id="inputEmail3" placeholder="Email">'
						    +'</div>'
						  +'</div>'
						  +'<div class="form-group">'
						    +'<label for="inputPassword3" class="col-sm-2 control-label">Password</label>'
						    +'<div class="col-sm-10">'
						      +'<input type="password" class="form-control" id="inputPassword3" placeholder="Password">'
						    +'</div>'
						  +'</div>'
						  +'<div class="form-group">'
						    +'<div class="col-sm-offset-2 col-sm-10">'
						      +'<div class="checkbox">'
						        +'<label>'
						          +'<input type="checkbox"> Remember me'
						        +'</label>'
						      +'</div>'
						    +'</div>'
						  +'</div>'
						+'</form>'
		      +'</div>'
		      +'<div class="modal-footer">'
		      	+'<div class="form-group">'
						  +'<div class="col-sm-offset-2 col-sm-10">'
								+'<button type="submit" class="btn btn-default">Sign in</button>'
						  +'</div>'
						+'</div>'
		      +'</div>'
		    +'</div>'
		  +'</div>'
		+'</div>'
		+'<!-- end Login Modal -->'
		+'<!-- Reg Modal -->'
		+'<div class="modal fade" id="regModal" tabindex="-1" role="dialog" aria-labelledby="regModalLabel">'
			+'<div class="modal-dialog" role="document">'
		    +'<div class="modal-content">'
					+'<div class="modal-header">'
		        +'<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>'
		        +'<h4 class="modal-title" id="regModalLabel">Register</h4>'
		      +'</div>'
		      +'<div class="modal-body">'
						+'<form class="form-horizontal">'
		      		+'<div class="form-group">'
								+'<label for="inputEmail3" class="col-sm-2 control-label">Name</label>'
						    +'<div class="col-sm-10">'
								+'<input type="email" class="form-control" id="inputEmail3" placeholder="Name">'
						    +'</div>'
						  +'</div>'
						  +'<div class="form-group">'
								+'<label for="inputEmail3" class="col-sm-2 control-label">Email</label>'
						    +'<div class="col-sm-10">'
								+'<input type="email" class="form-control" id="inputEmail3" placeholder="Email">'
						    +'</div>'
						  +'</div>'
						  +'<div class="form-group">'
								+'<label for="inputPassword3" class="col-sm-2 control-label">Password</label>'
						    +'<div class="col-sm-10">'
								+'<input type="password" class="form-control" id="inputPassword3" placeholder="Password">'
						    +'</div>'
						  +'</div>'
						  +'<div class="form-group">'
								+'<label for="inputPassword3" class="col-sm-2 control-label">Confirm Password</label>'
						    +'<div class="col-sm-10">'
								+'<input type="password" class="form-control" id="inputPassword3" placeholder="Confirm Password">'
						    +'</div>'
						  +'</div>'
						+'</form>'
		      +'</div>'
		      +'<div class="modal-footer">'
							+'<div class="form-group">'
						  +'<div class="col-sm-offset-2 col-sm-10">'
							+'<button type="submit" class="btn btn-default">Sign up</button>'
						  +'</div>'
						+'</div>'
		      +'</div>'
		    +'</div>'
		  +'</div>'
		+'</div>'
		+'<!-- end Reg Modal -->';
  return modals;
}